// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

import "solady/src/utils/LibString.sol";
import "./IGarden.sol";
import "./Sculpture.sol";
import "./ModConfigurable.sol";

library GardenContributions {
    function html(address garden, address data) external view returns (string memory html) {
        string memory symbol = ModConfigurable(data).unicodeSymbol();
        if (bytes(symbol).length == 0) symbol = unicode"⚘";
        uint256 guests = IGarden(garden).guests();
        uint256 flowers = IGarden(garden).flowers();
        html = string.concat(html,
            '<div class="w" id="guestbook"><div class="s">',
                '<div id="field1" class="field"></div>'
                '<br><br><br>',
                '<p style="text-align:center;">',
                'Guestbook',
                '<br><br>',
                'You may leave a flower here by sending 0.01 ETH (or multiples thereof)<br> to the show contract at <span class="a">',
                    LibString.toHexStringChecksummed(garden),
                '</span><br><br>',
                LibString.toString(guests),
                guests == 1 ? ' guest has' : ' guests have',
                ' planted ', LibString.toString(flowers),
                ' flower' , flowers == 1 ? '' : 's',
                '</p><br><br><br>',
                '<div id="field2" class="field"></div>',
                '<style>'
                    '.tooltip { font-size: 0.8em; background: white; border: 1px solid black; padding: 0.5em; width: 220px; }',
                    '.tooltip.r { text-align: right; }',
                    '.tooltip .address { overflow-wrap: break-word; }',
                '</style>',
                '<script>',
                    'document.addEventListener("DOMContentLoaded", () => {',
                    'const flowers = ', LibString.toString(IGarden(garden).flowers()), ';',
                    unicode'console.log(`Welcome to the ', Sculpture(garden).title(), '`);',
                    'console.log(` ', symbol, '                    ', symbol, '                  ', symbol, '\n',
                    '             ', symbol, '                       ', symbol, '\n',
                    '    ', symbol, '\n',
                    '                      ', symbol, '                     ', symbol, '\n\n',
                    '    Initializing garden with ${flowers} flowers\n\n',
                    '             ', symbol, '                         ', symbol, '\n',
                    symbol, '                        ', symbol, '                   ', symbol, '\n',
                    '    ', symbol, '                                ', symbol, '\n',
                    '                      ', symbol, '`);',
                    'function calculateThreshold(planted) {',
                        'const min = 30, max = 10000, lower = 0.99, higher = 0.8;',
                        'if (planted <= min) return lower;',
                        'if (planted >= max) return higher;',
                        'const normalized = (planted - min) / (max - min);',
                        'const logValue = Math.log10(1 + normalized * (10 - 1));',
                        'return higher + (lower - higher) * (1 - logValue);',
                    '}',
                    'function isConditionMet(planted, val) {',
                        'const threshold = calculateThreshold(planted);',
                        'return val > threshold || val < -threshold;',
                    '}',
                    'function gridNoise(x, z, seed) {',
                        'var n = (1619 * x + 31337 * z + 1013 * seed) & 0x7fffffff;',
                        'n = BigInt((n >> 13) ^ n);',
                        'n = n * (n * n * 60493n + 19990303n) + 1376312589n;',
                        'n = parseInt(n.toString(2).slice(-31), 2);',
                        'return 1 - n / 1073741824;',
                    '}',
                    'const width = 90;',
                    'let lines = [""], counter = 0, planted = 0;',
                    'while (planted < flowers) {',
                        'const val = gridNoise(counter % width, Math.floor(counter / width), 0xf);',
                        'const threshold = calculateThreshold(planted);',
                        'if (val > threshold || val < -threshold) {',
                            'lines[Math.floor(counter / width)] += `<a href="#flower${planted+1}" id="flower${planted+1}" style="position:relative;" data-flower-id="${planted+1}">', symbol, '</a>`;',
                            'planted++;',
                        '} else { lines[Math.floor(counter / width)] += " "; }',
                        'if (counter % width == (width-1) && planted < flowers) { lines.push(""); }',
                        'counter++;'
                    '}',
                    'lines = lines.reduce((acc, line) => { if (line.trim().length > 0) acc.push(line); return acc; }, []);',
                    'document.querySelector("#field1").innerHTML = lines.slice(0,Math.min(7,Math.ceil(lines.length/2))).join("\\n");',
                    'document.querySelector("#field2").innerHTML = lines.slice(Math.min(7,Math.ceil(lines.length/2))).join("\\n");',
                    'const flowerEls = document.querySelectorAll(".field a");',
                    'flowerEls.forEach((el) => {',
                        'el.addEventListener("mouseenter", (e) => {',
                        'const flowerId = e.target.dataset.flowerId;',
                        'if (flowerId) {',
                            'e.preventDefault();'
                            'showTooltip(flowerId);',
                        '}',
                    '});',
                    'el.addEventListener("mouseleave", (e) => {',
                    '    document.querySelectorAll(".tooltip").forEach((el) => el.remove());',
                    '});',
                    '});'
                    'window.addEventListener("resize", () => document.querySelectorAll(".tooltip").forEach((el) => el.remove()));',
                    'document.querySelectorAll(".field").forEach((el) => el.addEventListener("scroll", () => document.querySelectorAll(".tooltip").forEach((el) => el.remove())));',
                    'function showTooltip(flowerId) {',
                        'document.querySelectorAll(".tooltip").forEach((el) => el.remove());',
                        'const tooltip = document.createElement("div");',
                        'tooltip.classList.add("tooltip");',
                        'tooltip.id = "tooltip" + flowerId;',
                        'tooltip.innerHTML = `Loading Flower #${flowerId} ...`;',
                        'tooltip.style.position = "absolute";',
                        'const flower = document.getElementById("flower" + flowerId);',
                        'const clientRect = flower.getBoundingClientRect();',
                        'const offsetTop = window.pageYOffset || document.documentElement.scrollTop || document.body.scrollTop || 0;',
                        'tooltip.style.top = clientRect.top + (offsetTop) + flower.clientHeight + "px";',
                        'const offsetLeft = window.pageXOffset || document.documentElement.scrollLeft || document.body.scrollLeft || 0;',
                        'const leftPos = clientRect.left + offsetLeft;',
                        'tooltip.style.left = leftPos > window.innerWidth - 250 ? leftPos - 220 + "px" : leftPos + "px";',
                        'if (leftPos > window.innerWidth - 250) tooltip.classList.add("r");',
                        'document.body.appendChild(tooltip);',
                        'loadFlower(flowerId);',
                    '}',
                    'const fetchFlowerMemo = (() => {',
                    '    const cache = {};',
                    '    return async function(flowerId) {',
                    '        if (cache[flowerId]) return { ...cache[flowerId] };',
                    '        const res = await fetch("/flower/" + flowerId);',
                    '        const data = await res.json();',
                    '        cache[flowerId] = { ...data };',
                    '        return data;',
                    '    }',
                    '})();',
                    'async function loadFlower(flowerId) {',
                    '    try {',
                    '        const data = await fetchFlowerMemo(flowerId);',
                    '        console.log(`Loaded Flower #${flowerId}`, data);',
                    '        const tooltip = document.getElementById("tooltip" + flowerId);',
                    '        if (!tooltip) return;',
                    unicode'        tooltip.innerHTML = `Flower #${flowerId}<br> <span class="address">${data.planter}</span><br> ${formatTime(data.timestamp)}`;',
                    '    } catch (e) {',
                    '         console.error("Error loading flower", e);',
                    '    }',
                    '}',
                    'function formatTime(t) {',
                    '    const date = new Date(t * 1000);',
                    '    const options = { month: "long" };',
                    '    const month = new Intl.DateTimeFormat("en-US", options).format(date);',
                    '    const day = date.getDate();',
                    '    const year = date.getFullYear();',
                    '    let hours = date.getHours();',
                    '    const minutes = date.getMinutes().toString().padStart(2, "0");',
                    '    const amPm = hours >= 12 ? "pm" : "am";',
                    '    hours = hours % 12 || 12;',
                    '    return `${month} ${day}, ${year}, ${hours}:${minutes}${amPm}`;',
                    '}',
                    '});',
                '</script>',
            '</div></div>'
        );
    }
}